/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all registered projects (active + degraded) */
        get: operations["listProjects"];
        put?: never;
        /** Register a new project from a git repository path */
        post: operations["addProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one project; discriminates ok vs degraded */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Remove a project; stops sessions, cleans workspaces, unregisters */
        delete: operations["removeProject"];
        options?: never;
        head?: never;
        /** Patch behaviour-only fields (identity is frozen) */
        patch: operations["updateProjectConfig"];
        trace?: never;
    };
    "/api/v1/projects/{id}/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover a degraded project where automatic repair is available */
        post: operations["repairProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate cached config and re-scan the project registry */
        post: operations["reloadProjects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIError: {
            code: string;
            details?: {
                [key: string]: unknown;
            };
            error: string;
            message: string;
            requestId?: string;
        };
        AddInput: {
            name?: null | string;
            path: string;
            projectId?: null | string;
        };
        Degraded: {
            id: string;
            name: string;
            path: string;
            resolveError: string;
        };
        ListProjectsResponse: {
            projects: components["schemas"]["Summary"][];
        };
        Project: {
            agent?: string;
            defaultBranch: string;
            id: string;
            name: string;
            path: string;
            reactions?: {
                [key: string]: components["schemas"]["ReactionConfig"];
            };
            repo: string;
            runtime?: string;
            scm?: components["schemas"]["SCMConfig"];
            tracker?: components["schemas"]["TrackerConfig"];
        };
        ProjectGetResponse: {
            project: components["schemas"]["ProjectOrDegraded"];
            /** @enum {string} */
            status: "ok" | "degraded";
        };
        ProjectOrDegraded: components["schemas"]["Project"] | components["schemas"]["Degraded"];
        ProjectResponse: {
            project: components["schemas"]["Project"];
        };
        ReactionConfig: {
            action?: string;
            auto?: null | boolean;
            escalateAfter?: unknown;
            includeSummary?: null | boolean;
            message?: string;
            priority?: string;
            retries?: null | number;
            threshold?: string;
        };
        ReloadResult: {
            degradedCount: number;
            projectCount: number;
            reloaded: boolean;
        };
        RemoveResult: {
            projectId: string;
            removedStorageDir: boolean;
        };
        SCMConfig: {
            package?: string;
            path?: string;
            plugin?: string;
            webhook?: components["schemas"]["SCMWebhookConfig"];
        };
        SCMWebhookConfig: {
            deliveryHeader?: string;
            enabled?: null | boolean;
            eventHeader?: string;
            maxBodyBytes?: number;
            path?: string;
            secretEnvVar?: string;
            signatureHeader?: string;
        };
        Summary: {
            id: string;
            name: string;
            resolveError?: string;
            sessionPrefix: string;
        };
        TrackerConfig: {
            package?: string;
            path?: string;
            plugin?: string;
        };
        UpdateConfigInput: {
            agent?: null | string;
            reactions?: null | {
                [key: string]: components["schemas"]["ReactionConfig"];
            };
            runtime?: null | string;
            scm?: components["schemas"]["SCMConfig"];
            tracker?: components["schemas"]["TrackerConfig"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProjectsResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    addProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project identifier (registry key). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGetResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    removeProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project identifier (registry key). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    updateProjectConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project identifier (registry key). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConfigInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    repairProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project identifier (registry key). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
    reloadProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadResult"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIError"];
                };
            };
        };
    };
}
